package com.martim.lima.exercicio.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import java.io.Serializable;
import java.sql.Timestamp;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import lombok.NoArgsConstructor;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;


@Entity
@Data
@Table(name = "mortality_rate")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class MortalityRate implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private int year;

    @Column(nullable = false)
    private String country;

    @Column(nullable = false)
    private double femaleRate;

    @Column(nullable = false)
    private double maleRate;

    private long malePopulation;

    private long femalePopulation;

    @CreationTimestamp
    private Timestamp created_at;

    @UpdateTimestamp
    private Timestamp updated_at;
    // Additional fields for population numbers if needed

    // Constructors, getters, setters, and other methods are generated by Lombok
}